export const TRAINING_DATA_LIST_REQUEST = "TRAINING_DATA_LIST_REQUEST";
export const TRAINING_DATA_LIST_SUCCESS = "TRAINING_DATA_LIST_SUCCESS";
export const TRAINING_DATA_LIST_FAIL = "TRAINING_DATA_LIST_FAIL";
